server:
  port: 8001

#服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/dbspringcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:

#别名扫描  xml扫描
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.it.springcloud.entity