server:
  port: 80


eureka:
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-consumer-hystrix-order

#服务降级
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
  #设置feign 服务调用超时时间
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 10000